import dynamic from "next/dynamic";

// Bundle these components by default:
export { default as Image } from "../../_common/components/Image";
// export { default as Figure } from "../../_common/components/Figure";

// These (mostly very small) components are direct replacements for HTML tags generated by remark:
export { default as a } from "../../_common/components/Link";
export { default as code } from "../../_common/components/CodeHybrid";
// export { default as hr } from "../../_common/components/HorizontalRule";
export { H1 as h1, H2 as h2, H3 as h3, H4 as h4, H5 as h5, H6 as h6 } from "../../_common/components/Heading";
// export { UnorderedList as ul, OrderedList as ol, ListItem as li } from "../../_common/components/List";

// ...and these components are technically passed into all posts, but next/dynamic ensures they're loaded only
// when they're referenced in the individual mdx files.
export const IFrame = dynamic(() => import("../../_common/components/IFrame"));
export const Video = dynamic(() => import("../../_common/components/Video"));
// export const YouTube = dynamic(() => import("../../_common/components/YouTubeEmbed"));
// export const Tweet = dynamic(() => import("../../_common/components/TweetEmbed"));
// export const Gist = dynamic(() => import("../../_common/components/GistEmbed"));
export const CodePen = dynamic(() => import("../../_common/components/CodePenEmbed"));

// One-offs for specific posts:
// export const OctocatLink = dynamic(() => import("../../_common/components/OctocatLink"));
