import dynamic from "next/dynamic";

// Bundle these components by default:
export { default as Image } from "../../_common/components/Image";

// These (mostly very small) components are direct replacements for HTML tags generated by remark:
export { default as a } from "../../_common/components/Link";
export { default as code } from "../../_common/components/Code";
export { H1 as h1, H2 as h2, H3 as h3, H4 as h4, H5 as h5, H6 as h6 } from "../../_common/components/Heading";

// ...and these components are technically passed into all posts, but next/dynamic ensures they're loaded only
// when they're referenced in the individual mdx files.
export const IFrame = dynamic(() => import("../../_common/components/IFrame"));
export const Video = dynamic(() => import("../../_common/components/Video"));
export const CodePen = dynamic(() => import("../../_common/components/CodePen/CodePen"));
