# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    versioning-strategy: increase
    groups:
      nextjs:
        patterns:
          - "next"
          - "@next/*"
          - "eslint-config-next"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-is"
          - "@types/react"
          - "@types/react-dom"
          - "@types/react-is"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      mdx:
        patterns:
          - "remark-*"
          - "rehype-*"
          - "unified"
          - "@mdx-js/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
    ignore:
      - dependency-name: "@jakejarvis/eslint-config"
      - dependency-name: "@types/node"
      - dependency-name: "@types/prop-types"
    labels:
      - "📦 dependencies"
    commit-message:
      prefix: "📦 npm:"
    open-pull-requests-limit: 99
